import { Product } from '../models/Product';
import { ProductCategory } from '../models/ProductCategory';
import { ProductStatus } from '../models/ProductStatus';

// Change the return type if necessary
export const getProductList = (): Product[] => {
  const randomData = [
    {
      id: 1,
      name: 'Manzana',
      status: ProductStatus.Active,
      category: ProductCategory.Fruit,
      price: 2.5,
      stock: 7,
    },
    {
      id: 2,
      name: 'Banana',
      status: ProductStatus.Active,
      category: ProductCategory.Fruit,
      price: 1.75,
      stock: 3,
    },
    {
      id: 3,
      name: 'Zanahoria',
      status: ProductStatus.Active,
      category: ProductCategory.Vegetables,
      price: 3.0,
      stock: 25,
    },
    {
      id: 4,
      name: 'Lechuga',
      status: ProductStatus.Active,
      category: ProductCategory.Vegetables,
      price: 1.99,
      stock: 5,
    },
    {
      id: 5,
      name: 'Filete de Ternera',
      status: ProductStatus.Inactive,
      category: ProductCategory.Meat,
      price: 12.5,
      stock: 9,
    },
    {
      id: 6,
      name: 'Pechuga de Pollo',
      status: ProductStatus.Active,
      category: ProductCategory.Meat,
      price: 9.99,
      stock: 3,
    },
    {
      id: 7,
      name: 'Pescado',
      status: ProductStatus.Inactive,
      category: ProductCategory.Meat,
      price: 2.0,
      stock: 3,
    },
    {
      id: 8,
      name: 'Pato',
      status: ProductStatus.Active,
      category: ProductCategory.Meat,
      price: 1.5,
      stock: 4,
    },
    {
      id: 9,
      name: 'Zapallo',
      status: ProductStatus.Active,
      category: ProductCategory.Vegetables,
      price: 3.75,
      stock: 3,
    },
    {
      id: 10,
      name: 'Remolacha',
      status: ProductStatus.Inactive,
      category: ProductCategory.Vegetables,
      price: 2.25,
      stock: 0,
    },
    {
      id: 11,
      name: 'Limon',
      status: ProductStatus.Active,
      category: ProductCategory.Fruit,
      price: 1.99,
      stock: 7,
    },
    {
      id: 12,
      name: 'Tomate',
      status: ProductStatus.Active,
      category: ProductCategory.Vegetables,
      price: 2.25,
      stock: 2,
    },
    {
      id: 13,
      name: 'Pera',
      status: ProductStatus.Inactive,
      category: ProductCategory.Fruit,
      price: 3.5,
      stock: 0,
    },
    {
      id: 14,
      name: 'Cebolla',
      status: ProductStatus.Inactive,
      category: ProductCategory.Vegetables,
      price: 1.0,
      stock: 0,
    },
    {
      id: 15,
      name: 'Salmón Ahumado',
      status: ProductStatus.Inactive,
      category: ProductCategory.Meat,
      price: 15.99,
      stock: 1,
    },
    {
      id: 16,
      name: 'Aguacate',
      status: ProductStatus.Active,
      category: ProductCategory.Fruit,
      price: 2.99,
      stock: 17,
    },
    {
      id: 17,
      name: 'Frutilla',
      status: ProductStatus.Inactive,
      category: ProductCategory.Fruit,
      price: 3.49,
      stock: 12,
    },
    {
      id: 18,
      name: 'Naranja',
      status: ProductStatus.Active,
      category: ProductCategory.Fruit,
      price: 1.75,
      stock: 13,
    },
    {
      id: 19,
      name: 'Patata',
      status: ProductStatus.Active,
      category: ProductCategory.Vegetables,
      price: 1.25,
      stock: 1,
    },
    {
      id: 20,
      name: 'Costillas de Cerdo',
      status: ProductStatus.Inactive,
      category: ProductCategory.Meat,
      price: 10.75,
      stock: 1,
    },
  ];

  return randomData;
};
